// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajvqvpbfvpsqxjxyfiul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdnF2cGJmdnBzcXhqeHlmaXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5NzMzMDQsImV4cCI6MjA4NjU0OTMwNH0.ttD5G1TCImk6mqwEnNiMhfzEbDWI43o3-8KtiooAEXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});